<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portofolio - FreelanceHub</title>
    <style>
        :root { --ink: #18212b; --muted: #718096; --line: #e6e9ed; --accent: #d97745; --dark: #17232b; }
        * { box-sizing: border-box; } body { margin: 0; color: var(--ink); background: radial-gradient(circle at 90% 0%, #fce7d9 0, transparent 30%), #f4f6f4; font-family: Arial, sans-serif; }
        .app { display: flex; min-height: 100vh; } .sidebar { width: 238px; padding: 28px 18px; background: var(--dark); color: #fff; } .brand { padding: 0 14px 30px; font-size: 21px; font-weight: 700; } .eyebrow { padding: 0 14px 10px; color: #8fa0a8; font-size: 11px; text-transform: uppercase; letter-spacing: 1.5px; } .nav a { display: block; padding: 12px 14px; margin: 4px 0; color: #cbd5d9; border-radius: 8px; text-decoration: none; font-size: 14px; } .nav a:hover, .nav a.active { background: #30424a; color: white; }
        .main { flex: 1; padding: 30px clamp(22px, 5vw, 70px); } .topbar, .heading, .card-footer { display: flex; align-items: center; justify-content: space-between; gap: 16px; } .topbar { margin-bottom: 42px; color: var(--muted); font-size: 14px; } .profile { display: flex; align-items: center; gap: 10px; color: var(--ink); font-weight: 700; } .avatar { display: grid; place-items: center; width: 36px; height: 36px; border-radius: 50%; background: #f1c6ad; color: #71391f; } h1 { margin: 0; font-size: clamp(28px, 4vw, 42px); letter-spacing: -1px; } .subtitle { margin: 9px 0 0; color: var(--muted); } .button { display: inline-block; border: 0; border-radius: 7px; padding: 12px 16px; color: white; background: #a94d25; text-decoration: none; font-size: 14px; cursor: pointer; } .stats { display: grid; grid-template-columns: repeat(2, 220px); gap: 14px; margin: 30px 0; } .stat, .card, .empty { background: #fff; border: 1px solid var(--line); border-radius: 10px; box-shadow: 0 8px 24px rgba(24,33,43,.04); } .stat { padding: 18px 20px; } .stat strong { display: block; font-size: 27px; } .stat span { color: var(--muted); font-size: 13px; } .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(270px, 1fr)); gap: 18px; } .card { padding: 22px; } .preview { height: 116px; display: grid; place-items: center; border-radius: 8px; background: linear-gradient(135deg, #f8d8c5, #e9eff0); color: #a94d25; font-size: 32px; font-weight: 700; } .card h2 { margin: 18px 0 8px; font-size: 19px; } .card p { color: var(--muted); line-height: 1.5; font-size: 14px; } .edit { color: #a94d25; text-decoration: none; font-size: 13px; font-weight: 700; } .delete { border: 0; background: none; color: #b42318; cursor: pointer; font-size: 13px; } .empty { padding: 48px 24px; text-align: center; grid-column: 1 / -1; } .empty p { color: var(--muted); } .alert { margin-bottom: 18px; padding: 13px 16px; border-radius: 7px; background: #dff4e6; color: #21613a; } @media (max-width: 760px) { .sidebar { display: none; } .main { padding: 22px 16px; } .heading { align-items: flex-start; flex-direction: column; } .stats { grid-template-columns: 1fr 1fr; } }
    </style>
</head>
<body><div class="app"><aside class="sidebar"><div class="brand">FreelanceHub</div><div class="eyebrow">Workspace</div><nav class="nav"><a href="/freelancer/dashboard">Dashboard</a><a href="{{ route('jasa.index') }}">Jasa Saya</a><a class="active" href="{{ route('portfolios.index') }}">Portofolio</a><a href="{{ route('categories.index') }}">Kategori</a><a href="/freelancer/profil">Profil Saya</a></nav></aside><main class="main"><div class="topbar"><span>Workspace / Portofolio</span><div class="profile"><span class="avatar">F</span> Freelancer</div></div>@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif<div class="heading"><div><h1>Portofolio</h1><p class="subtitle">Tampilkan karya terbaik untuk membangun kepercayaan klien.</p></div><a class="button" href="{{ route('portfolios.create') }}">+ Tambah Karya</a></div><div class="stats"><div class="stat"><strong>{{ $portfolios->count() }}</strong><span>Total karya</span></div><div class="stat"><strong>{{ $portfolios->pluck('service_id')->unique()->count() }}</strong><span>Jasa terkait</span></div></div><div class="grid">@forelse($portfolios as $portfolio)<article class="card"><div class="preview">KARYA</div><h2>{{ $portfolio->caption }}</h2><p>{{ $portfolio->service->title }}</p><p>{{ $portfolio->file_path }}</p><div class="card-footer"><a class="edit" href="{{ route('portfolios.edit', $portfolio) }}">Edit karya</a><form action="{{ route('portfolios.destroy', $portfolio) }}" method="POST" onsubmit="return confirm('Hapus portofolio ini?')">@csrf @method('DELETE')<button class="delete" type="submit">Hapus</button></form></div></article>@empty<div class="empty"><h2>Belum ada portofolio</h2><p>Tambahkan karya pertama agar klien bisa melihat kemampuanmu.</p><a class="button" href="{{ route('portfolios.create') }}">Tambah Karya Pertama</a></div>@endforelse</div></main></div></body>
</html>
