<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kategori - FreelanceHub</title>
    <style>
        :root { --ink:#18212b; --muted:#718096; --line:#e6e9ed; --dark:#17232b; --accent:#a94d25; } *{box-sizing:border-box} body{margin:0;color:var(--ink);background:radial-gradient(circle at 90% 0%,#fce7d9 0,transparent 30%),#f4f6f4;font-family:Arial,sans-serif}.app{display:flex;min-height:100vh}.sidebar{width:238px;padding:28px 18px;background:var(--dark);color:#fff}.brand{padding:0 14px 30px;font-size:21px;font-weight:700}.eyebrow{padding:0 14px 10px;color:#8fa0a8;font-size:11px;text-transform:uppercase;letter-spacing:1.5px}.nav a{display:block;padding:12px 14px;margin:4px 0;color:#cbd5d9;border-radius:8px;text-decoration:none;font-size:14px}.nav a:hover,.nav a.active{background:#30424a;color:#fff}.main{flex:1;padding:30px clamp(22px,5vw,70px)}.topbar,.heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.topbar{margin-bottom:42px;color:var(--muted);font-size:14px}.profile{display:flex;align-items:center;gap:10px;color:var(--ink);font-weight:700}.avatar{display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:#f1c6ad;color:#71391f}h1{margin:0;font-size:clamp(28px,4vw,42px);letter-spacing:-1px}.subtitle{margin:9px 0 0;color:var(--muted)}.button{display:inline-block;border:0;border-radius:7px;padding:12px 16px;color:#fff;background:var(--accent);text-decoration:none;font-size:14px;cursor:pointer}.stats{display:grid;grid-template-columns:220px;gap:14px;margin:30px 0}.stat,.panel{background:#fff;border:1px solid var(--line);border-radius:10px;box-shadow:0 8px 24px rgba(24,33,43,.04)}.stat{padding:18px 20px}.stat strong{display:block;font-size:27px}.stat span{color:var(--muted);font-size:13px}.panel{overflow:hidden}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:18px 20px;text-align:left;border-bottom:1px solid var(--line)}.table th{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.6px}.table td{font-size:14px}.pill{display:inline-block;padding:6px 9px;border-radius:99px;background:#eef4ef;color:#477054;font-size:12px}.edit{color:var(--accent);font-weight:700;text-decoration:none;margin-right:14px}.delete{border:0;background:none;color:#b42318;cursor:pointer;font-size:13px}.alert{margin-bottom:18px;padding:13px 16px;border-radius:7px;background:#dff4e6;color:#21613a}.empty{text-align:center;color:var(--muted)}@media(max-width:760px){.sidebar{display:none}.main{padding:22px 16px}.heading{align-items:flex-start;flex-direction:column}.panel{overflow:auto}.table{min-width:600px}}
    </style>
</head>
<body><div class="app"><aside class="sidebar"><div class="brand">FreelanceHub</div><div class="eyebrow">Workspace</div><nav class="nav"><a href="/freelancer/dashboard">Dashboard</a><a href="{{ route('jasa.index') }}">Jasa Saya</a><a href="{{ route('portfolios.index') }}">Portofolio</a><a class="active" href="{{ route('categories.index') }}">Kategori</a><a href="/freelancer/profil">Profil Saya</a></nav></aside><main class="main"><div class="topbar"><span>Workspace / Kategori</span><div class="profile"><span class="avatar">F</span> Freelancer</div></div>@if(session('success'))<div class="alert">{{ session('success') }}</div>@endif<div class="heading"><div><h1>Kategori</h1><p class="subtitle">Susun layanan berdasarkan keahlian yang kamu tawarkan.</p></div><a class="button" href="{{ route('categories.create') }}">+ Tambah Kategori</a></div><div class="stats"><div class="stat"><strong>{{ $categories->count() }}</strong><span>Total kategori</span></div></div><div class="panel"><table class="table"><thead><tr><th>Nama kategori</th><th>Slug</th><th>Aksi</th></tr></thead><tbody>@forelse($categories as $category)<tr><td><strong>{{ $category->category_name }}</strong></td><td><span class="pill">{{ $category->slug }}</span></td><td><a class="edit" href="{{ route('categories.edit', $category) }}">Edit</a><form style="display:inline" action="{{ route('categories.destroy', $category) }}" method="POST" onsubmit="return confirm('Hapus kategori ini?')">@csrf @method('DELETE')<button class="delete" type="submit">Hapus</button></form></td></tr>@empty<tr><td class="empty" colspan="3">Belum ada kategori. Tambahkan kategori pertama untuk mengelompokkan jasa.</td></tr>@endforelse</tbody></table></div></main></div></body>
</html>
